# Generated by Django 2.2.4 on 2019-09-25 05:07

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kesehatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diare', models.IntegerField()),
                ('gatal', models.IntegerField()),
                ('demam', models.IntegerField()),
                ('batuk', models.IntegerField()),
                ('Flu', models.IntegerField()),
                ('Lainya', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='kondisi_lingkungan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luas_tanah', models.IntegerField()),
                ('jumlah_santri', models.IntegerField()),
                ('jumlah_santriwati', models.IntegerField()),
                ('jarak_pemukiman', models.IntegerField()),
                ('jumlah_kk_sekitar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formal', models.IntegerField()),
                ('non_formal', models.IntegerField()),
                ('nama_pimpinan', models.CharField(max_length=50)),
                ('jenis_pendidikan', multiselectfield.db.fields.MultiSelectField(choices=[('Tahfiz / Hafiz', 'Tahfiz / Hafiz'), ('Kitab Kuning', 'Kitab Kuning')], max_length=27)),
                ('senin', models.CharField(default='', editable=False, max_length=50)),
                ('selasa', models.CharField(default='', editable=False, max_length=50)),
                ('rabu', models.CharField(default='', editable=False, max_length=50)),
                ('kamis', models.CharField(default='', editable=False, max_length=50)),
                ('jumat', models.CharField(default='', editable=False, max_length=50)),
                ('sabtu', models.CharField(default='', editable=False, max_length=50)),
                ('minggu', models.CharField(default='', editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='petugas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_petugas', models.CharField(max_length=50)),
                ('nama_koordinator', models.CharField(max_length=50)),
                ('nama_pemberi_informasi', models.CharField(default='', editable=False, max_length=50)),
                ('tgl_pelaksanaan', models.DateTimeField()),
                ('tgl_pemeriksaan', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='prestasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('santri_penghafal', models.IntegerField()),
                ('santriwati_penghafal', models.IntegerField()),
                ('santri_baca_kitabkuning', models.IntegerField()),
                ('santriwati_baca_kitabkuning', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='profil_pimpinan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pimpinan', models.CharField(max_length=50)),
                ('pendidikan', models.CharField(max_length=100)),
                ('jumlah_keluarga', models.IntegerField()),
                ('pekerjaan_diluar_dayah', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ringkasan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pekerja', models.CharField(max_length=50)),
                ('smp', models.IntegerField()),
                ('sma', models.IntegerField()),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sarana_prasarana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jml_kantor', models.IntegerField(default=0)),
                ('luas_kantor', models.IntegerField(default=0)),
                ('jml_perpustakaan', models.IntegerField(default=0)),
                ('luas_perpustakaan', models.IntegerField(default=0)),
                ('jml_kamarguru', models.IntegerField(default=0)),
                ('luas_kamarguru', models.IntegerField(default=0)),
                ('jml_kelas_santri', models.IntegerField(default=0)),
                ('luas_kelas_santri', models.IntegerField(default=0)),
                ('jml_kelas_santriwati', models.IntegerField(default=0)),
                ('luas_kelas_santriwati', models.IntegerField(default=0)),
                ('kapasitas_siswa_perkelas', models.IntegerField(default=0)),
                ('jml_kamar_santri', models.IntegerField(default=0)),
                ('luas_kamar_santri', models.IntegerField(default=0)),
                ('jml_kamar_santriwati', models.IntegerField(default=0)),
                ('luas_kamar_santriwati', models.IntegerField(default=0)),
                ('jml_kamar_tamu', models.IntegerField(default=0)),
                ('luas_kamar_tamu', models.IntegerField(default=0)),
                ('jml_mushola', models.IntegerField(default=0)),
                ('luas_mushola', models.IntegerField(default=0)),
                ('jml_dapur_umum', models.IntegerField(default=0)),
                ('luas_dapur_umum', models.IntegerField(default=0)),
                ('jml_ruang_makan', models.IntegerField(default=0)),
                ('luas_ruang_makan', models.IntegerField(default=0)),
                ('jml_ruangkegiatan_aula', models.IntegerField()),
                ('luas_ruangkegiatan_aula', models.IntegerField()),
                ('jml_komputer', models.IntegerField()),
                ('jml_pengeras_suara', models.IntegerField()),
                ('lainya', models.CharField(blank='true', max_length=100)),
                ('sumber_air_untuk_minum', models.CharField(blank='true', max_length=200)),
                ('sumber_air_untuk_mandi_cuci', models.CharField(blank='true', max_length=200)),
                ('jml_kamar_madi', models.IntegerField(default=0)),
                ('luas_kamar_mandi', models.IntegerField(default=0)),
                ('jml_kantin', models.IntegerField(default=0)),
                ('luas_kantin', models.IntegerField(default=0)),
                ('sarana_olahraga', models.CharField(blank='true', max_length=200)),
                ('jml_tempat_wudhu', models.IntegerField(default=0)),
                ('luas_tempat_wudhu', models.IntegerField(default=0)),
                ('sarana_tidur', models.CharField(blank='true', max_length=200)),
                ('jml_dipan', models.IntegerField(blank='true', default=0)),
                ('kapasitas_dipan', models.IntegerField(blank='true', default=0)),
                ('tidak_menggunakan_dipan', models.BooleanField(default=0)),
                ('alas_tidur', models.CharField(blank='true', max_length=200)),
                ('lantai_tersedia', models.CharField(blank='true', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pengenalan_dayah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dayah', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=250)),
                ('pemimpin_dayah', models.CharField(max_length=50)),
                ('tahun_berdiri', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=50)),
                ('type_dayah', models.CharField(max_length=50)),
                ('kesehatan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='profil.kesehatan', verbose_name='Kesehatan')),
                ('kondisi_lingkungan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='profil.kondisi_lingkungan', verbose_name='Kondisi Lingkungan')),
                ('pendidikan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='profil.pendidikan', verbose_name='Pendidikan')),
                ('petugas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='profil.petugas', verbose_name='Petugas')),
                ('prestasi', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='profil.prestasi', verbose_name='Prestasi')),
                ('profil_pimpinan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='profil.profil_pimpinan', verbose_name='Profil_pimpinan')),
                ('ringkasan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='profil.ringkasan', verbose_name='Ringkasan Dayah')),
                ('sarana_prasarana', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='profil.sarana_prasarana', verbose_name='Sarana Prasarana')),
            ],
        ),
        migrations.AddField(
            model_name='kondisi_lingkungan',
            name='pendidikan_pengajar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='profil.ringkasan', verbose_name='Ringkasan'),
        ),
    ]
