# Generated by Django 2.2.4 on 2019-09-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringkasan',
            name='s1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ringkasan',
            name='s2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ringkasan',
            name='s3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ringkasan',
            name='sma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ringkasan',
            name='smp',
            field=models.IntegerField(default=0),
        ),
    ]
