# Generated by Django 2.2.4 on 2019-09-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20190930_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petugas',
            name='tgl_pelaksanaan',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='tgl_pemeriksaan',
            field=models.DateField(),
        ),
    ]
