# Generated by Django 2.2.4 on 2019-09-30 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20190930_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petugas',
            name='tgl_pelaksanaan',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='tgl_pemeriksaan',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
