# Generated by Django 2.2.4 on 2019-09-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_auto_20190930_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesehatan',
            name='Lainya',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='jumat',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='kamis',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='minggu',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='rabu',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='sabtu',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='selasa',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='senin',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pengenalan_dayah',
            name='no_hp',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='nama_pemberi_informasi',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profil_pimpinan',
            name='pekerjaan_diluar_dayah',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sarana_prasarana',
            name='alas_tidur',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sarana_prasarana',
            name='lainya',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sarana_prasarana',
            name='lantai_tersedia',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sarana_prasarana',
            name='sarana_olahraga',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sarana_prasarana',
            name='sarana_tidur',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sarana_prasarana',
            name='sumber_air_untuk_mandi_cuci',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sarana_prasarana',
            name='sumber_air_untuk_minum',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
