# Generated by Django 2.2.4 on 2019-09-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_auto_20190930_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendidikan',
            name='nama_pimpinan',
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='formal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pendidikan',
            name='non_formal',
            field=models.IntegerField(default=0),
        ),
    ]
