# Generated by Django 2.2.4 on 2019-10-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_auto_20190930_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_dapur_umum',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_kamar_mandi',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_kamar_santri',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_kamar_santriwati',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_kamar_tamu',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_kamarguru',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_kantin',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_kantor',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_kelas_santri',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_kelas_santriwati',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_mushola',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_perpustakaan',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_ruang_makan',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_ruangkegiatan_aula',
        ),
        migrations.RemoveField(
            model_name='sarana_prasarana',
            name='luas_tempat_wudhu',
        ),
    ]
