# Generated by Django 2.2.4 on 2019-10-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_auto_20191015_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ringkasan',
            old_name='Nama_dayah',
            new_name='nama_dayah',
        ),
    ]
