# Generated by Django 2.2.4 on 2019-10-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0010_auto_20191015_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='ringkasan',
            name='test',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
