# Generated by Django 2.2.4 on 2019-10-23 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0011_ringkasan_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringkasan',
            name='nama_dayah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.pengenalan_dayah'),
        ),
    ]
