# Generated by Django 2.2.4 on 2019-10-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0012_auto_20191023_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesehatan',
            name='nama_dayah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.pengenalan_dayah'),
        ),
        migrations.AddField(
            model_name='kondisi_lingkungan',
            name='nama_dayah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.pengenalan_dayah'),
        ),
        migrations.AddField(
            model_name='pendidikan',
            name='nama_dayah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.pengenalan_dayah'),
        ),
        migrations.AddField(
            model_name='petugas',
            name='nama_dayah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.pengenalan_dayah'),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='nama_dayah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.pengenalan_dayah'),
        ),
        migrations.AddField(
            model_name='profil_pimpinan',
            name='nama_dayah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.pengenalan_dayah'),
        ),
        migrations.AddField(
            model_name='sarana_prasarana',
            name='nama_dayah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.pengenalan_dayah'),
        ),
        migrations.AlterField(
            model_name='ringkasan',
            name='nama_dayah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.pengenalan_dayah'),
        ),
    ]
