# Generated by Django 2.2.4 on 2019-10-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0013_auto_20191023_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ringkasan',
            name='test',
        ),
    ]
