# Generated by Django 2.2.4 on 2019-10-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0014_remove_ringkasan_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengenalan_dayah',
            options={'verbose_name': 'FORM DAYAH'},
        ),
    ]
