# Generated by Django 2.2.4 on 2019-10-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0016_data_foto_data_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_foto',
            name='foto',
            field=models.ImageField(blank='true', upload_to='profil/static/img/profil_img'),
        ),
    ]
