# Generated by Django 2.2.4 on 2019-12-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0019_auto_20191219_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengenalan_dayah',
            name='foto_profil',
            field=models.ImageField(blank='true', upload_to='static/profil_img/'),
        ),
    ]
