# Generated by Django 2.2.4 on 2020-01-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0021_auto_20200104_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kondisi_lingkungan',
            name='jarak_pemukiman',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kondisi_lingkungan',
            name='jumlah_kk_sekitar',
            field=models.IntegerField(default=0),
        ),
    ]
